version: "3.8"
services:
  app:
    container_name: app
    image: app_image
    env_file:
      - .env
    build: .
    volumes:
      - .:/code
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports: 
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data

  test_db:
    image: postgres:15
    container_name: test_db
    ports:
      - "${TEST_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_HOST=${TEST_HOST}
      - POSTGRES_DB=${TEST_DB}
      - POSTGRES_USER=${TEST_USERNAME}
      - POSTGRES_PASSWORD=${TEST_PASSWORD}
    env_file:
      - .env
    volumes:
      - test_db-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: "local"
  redis:
  test_db-data:

networks:
  default:
    name: app_main