version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    container_name: app_container
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  redis:
    image: redis
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data

volumes:
  postgres-data:
  redis: