version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    container_name: app_container
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  redis:
    image: redis
    container_name: redis
    ports: 
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
     - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  redis:
  pgadmin-data: