"""4_workflow

Revision ID: 041360e65a28
Revises: ef7f761d5fd5
Create Date: 2023-03-25 16:51:37.276811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041360e65a28'
down_revision = 'ef7f761d5fd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_workflow',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('workflow_user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_quiz_id', sa.Integer(), nullable=False),
    sa.Column('workflow_company_id', sa.Integer(), nullable=False),
    sa.Column('workflow_record_correct_answers', sa.Integer(), nullable=True),
    sa.Column('workflow_record_all_questions', sa.Integer(), nullable=False),
    sa.Column('workflow_record_result', sa.Float(), nullable=True),
    sa.Column('workflow_quiz_correct_answers', sa.Integer(), nullable=True),
    sa.Column('workflow_quiz_all_questions', sa.Integer(), nullable=False),
    sa.Column('workflow_quiz_result', sa.Float(), nullable=True),
    sa.Column('workflow_company_correct_answers', sa.Integer(), nullable=True),
    sa.Column('workflow_company_all_questions', sa.Integer(), nullable=False),
    sa.Column('workflow_company_result', sa.Float(), nullable=True),
    sa.Column('workflow_system_correct_answers', sa.Integer(), nullable=True),
    sa.Column('workflow_system_all_questions', sa.Integer(), nullable=False),
    sa.Column('workflow_system_result', sa.Float(), nullable=True),
    sa.Column('workflow_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_company_id'], ['company.company_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['workflow_quiz_id'], ['quiz.quiz_id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['workflow_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_workflow')
    # ### end Alembic commands ###
