"""empty message

Revision ID: 0cc97e5c66c9
Revises: abe6966994df
Create Date: 2023-02-28 08:31:53.359879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc97e5c66c9'
down_revision = 'abe6966994df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
