"""2

Revision ID: 20f79823a354
Revises: c77e9ce5fa0d
Create Date: 2023-03-08 17:46:31.258475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f79823a354'
down_revision = 'c77e9ce5fa0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'created_at')
    # ### end Alembic commands ###
