"""4

Revision ID: 3cbe73733cea
Revises: ebf0979f385a
Create Date: 2023-03-13 13:34:16.141812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbe73733cea'
down_revision = 'ebf0979f385a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'user_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('User_user_username_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_user_username_key', 'User', ['user_username'])
    op.alter_column('User', 'user_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
