"""1

Revision ID: 64f95d3bf1f3
Revises: 
Create Date: 2023-03-17 22:06:30.862819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f95d3bf1f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_password', sa.String(), nullable=False),
    sa.Column('user_first_name', sa.String(), nullable=True),
    sa.Column('user_last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_owner_id', sa.Integer(), nullable=False),
    sa.Column('company_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_owner_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('invite',
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('invite_to_user_id', sa.Integer(), nullable=False),
    sa.Column('invite_from_company_id', sa.Integer(), nullable=False),
    sa.Column('invite_message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invite_from_company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_to_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invite_id')
    )
    op.create_table('membership',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('membership_user_id', sa.Integer(), nullable=False),
    sa.Column('membership_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membership_company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('request_from_user_id', sa.Integer(), nullable=False),
    sa.Column('request_to_company_id', sa.Integer(), nullable=False),
    sa.Column('request_message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_from_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_to_company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('membership')
    op.drop_table('invite')
    op.drop_table('company')
    op.drop_table('user')
    # ### end Alembic commands ###
