"""5_notification

Revision ID: c07a07d3a2db
Revises: 041360e65a28
Create Date: 2023-04-03 16:27:06.007536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07a07d3a2db'
down_revision = '041360e65a28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('notification_user_id', sa.Integer(), nullable=False),
    sa.Column('notification_quiz_id', sa.Integer(), nullable=False),
    sa.Column('notification_company_id', sa.Integer(), nullable=False),
    sa.Column('notification_text', sa.String(), nullable=False),
    sa.Column('notification_status', sa.Boolean(), nullable=False),
    sa.Column('notification_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['notification_company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_quiz_id'], ['quiz.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
