"""2

Revision ID: eb276f3b8958
Revises: 64f95d3bf1f3
Create Date: 2023-03-18 09:53:43.245798

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'eb276f3b8958'
down_revision = '64f95d3bf1f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('membership_role', sqlalchemy_utils.types.choice.ChoiceType([
        ("owner", "owner"), 
        ("admin", "admin"),
        ("user", "user")
    ]), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership', 'membership_role')
    # ### end Alembic commands ###
