"""3

Revision ID: ebf0979f385a
Revises: 20f79823a354
Create Date: 2023-03-11 12:01:55.565872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf0979f385a'
down_revision = '20f79823a354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'user_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'user_first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'user_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'user_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'user_first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'user_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
