"""3

Revision ID: ef7f761d5fd5
Revises: eb276f3b8958
Create Date: 2023-03-24 11:04:09.005889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef7f761d5fd5'
down_revision = 'eb276f3b8958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('quiz_name', sa.String(), nullable=False),
    sa.Column('quiz_description', sa.String(), nullable=True),
    sa.Column('quiz_frequency_in_days', sa.Integer(), nullable=False),
    sa.Column('quiz_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('quiz_question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_choices', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('question_answer', sa.String(), nullable=False),
    sa.Column('question_quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_quiz_id'], ['quiz.quiz_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_question')
    op.drop_table('quiz')
    # ### end Alembic commands ###
